name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Connect to scope at '192.168.1.100'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Error Message/Traceback
      description: If applicable, paste the full error traceback
      placeholder: Paste error message here
      render: python
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: e.g., Windows 11, Ubuntu 22.04, macOS 14.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.11.5
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of SCPI-Instrument-Control?
      placeholder: e.g., 0.2.5
    validations:
      required: true

  - type: input
    id: scope-model
    attributes:
      label: Oscilloscope Model
      description: What oscilloscope model are you using?
      placeholder: e.g., SDS824X HD, SDS1104X-E
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of the package
          required: false
        - label: I have tested with real hardware (if applicable)
          required: false
